-- Number Challenge Pro database
-- Run this in Supabase SQL Editor.
create table if not exists public.players (
  telegram_id text primary key,
  username text,
  display_name text not null default 'Player',
  total_points integer not null default 0,
  games_played integer not null default 0,
  best_score integer not null default 0,
  streak integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  telegram_id text not null,
  score integer not null default 0,
  correct_answers integer not null default 0,
  accuracy integer not null default 0,
  played_at timestamptz not null default now()
);

alter table public.players enable row level security;
alter table public.game_results enable row level security;

drop policy if exists "Public leaderboard read" on public.players;
create policy "Public leaderboard read" on public.players
for select to anon, authenticated using (true);

drop policy if exists "Player upsert" on public.players;
create policy "Player upsert" on public.players
for insert to anon, authenticated with check (true);

drop policy if exists "Player update" on public.players;
create policy "Player update" on public.players
for update to anon, authenticated using (true) with check (true);

drop policy if exists "Game results insert" on public.game_results;
create policy "Game results insert" on public.game_results
for insert to anon, authenticated with check (true);

create index if not exists players_points_idx on public.players(total_points desc);
create index if not exists game_results_telegram_idx on public.game_results(telegram_id);
